language: python
python:
  - '2.7'

before_install:
  - sudo apt-get install libgsl2
  - export GSLDIR=$(gsl-config --prefix)

install:
    pip install -r NuRadioMC/test/requirements.txt

before_script:
  - wget https://github.com/nu-radio/radiotools/archive/master.zip -O /tmp/radiotools.zip
  - unzip /tmp/radiotools.zip
  - mv radiotools-master radiotools
  - export PYTHONPATH=$PWD/radiotools
  - wget https://github.com/nu-radio/NuRadioReco/archive/master.zip -O /tmp/NuRadioReco.zip
  - unzip /tmp/NuRadioReco.zip
  - mv NuRadioReco-master NuRadioReco
  - export PYTHONPATH=$PYTHONPATH:$PWD/NuRadioReco
  - export PYTHONPATH=$PYTHONPATH:$PWD
  - wget http://arianna.ps.uci.edu/~arianna/data/AntennaModels/createLPDA_100MHz_InfFirn/createLPDA_100MHz_InfFirn.pkl
  - mkdir -p /home/travis/build/nu-radio/NuRadioMC/NuRadioReco/NuRadioReco/detector/AntennaModels/createLPDA_100MHz_InfFirn
  - mv createLPDA_100MHz_InfFirn.pkl /home/travis/build/nu-radio/NuRadioMC/NuRadioReco/NuRadioReco/detector/AntennaModels/createLPDA_100MHz_InfFirn/
  - wget http://arianna.ps.uci.edu/~arianna/data/AntennaModels/bicone_v8_InfFirn/bicone_v8_InfFirn.pkl
  - mkdir -p /home/travis/build/nu-radio/NuRadioMC/NuRadioReco/NuRadioReco/detector/AntennaModels/bicone_v8_InfFirn
  - mv bicone_v8_InfFirn.pkl /home/travis/build/nu-radio/NuRadioMC/NuRadioReco/NuRadioReco/detector/AntennaModels/bicone_v8_InfFirn/

script:
  - NuRadioMC/test/T02RunSimulation.py NuRadioMC/test/1e18_output_reference.hdf5 NuRadioMC/test/surface_station_1GHz.json NuRadioMC/test/config.yaml NuRadioMC/test/1e18_output.hdf5
  - NuRadioMC/test/T03validate.py NuRadioMC/test/1e18_output.hdf5 NuRadioMC/test/1e18_output_reference.hdf5